server:
  port: 8084

spring:
  application:
    name: product
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: 'jbeanny'
    password: 'password'
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka